### GENERAL SETTINGS ###

# Site settings
title: Valtrix Systems
punchline: An IP/SoC Validation Company
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: UA-68394244-1 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.valtrix.in"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/company/valtrix-systems
  - title: facebook
    url: https://www.facebook.com/valtrixsystems
  - title: twitter
    url: https://twitter.com/ValtrixSystems
  - title: google-plus
    url: https://plus.google.com/116801274163398376485
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Valtrix Technologies Pvt. Ltd.
    - "#No 1462, 25th Cross,"
    - HSR Layout Sector 2,
    - Bangalore - 560102, India.
email: contact@valtrix.in
tel:
  - nos:
    - +91 98457 35129
    - +91 99001 04342


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Shajid Thiruvathodi
    position: Director & Co-founder
    text: Shajid is a seasoned validation engineer and has worked on creating a number of RIS and focused design verification tools which have been very effective in uncovering bugs from pre-silicon to post-silicon. In ARM, Shajid conceived and designed software tools from scratch for CPU and I/O subsystem. He has also been a modeling engineer and has helped create functional models of ARM A, R and M class processors and micro controllers. In IBM, he was working on development of multiple software tools which were used for the validation of a broad range of PowerPC based systems. He is an avid footballer and takes keen interest in all things technical.
    img: dflt-team-pic.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sthiruva@valtrix.in
      - title: twitter
        url: http://twitter.com/sthiruva
      - title: linkedin
        url: https://in.linkedin.com/pub/shajid-thiruvathodi/6/108/49b
  - name: Shubhodeep Roy Choudhury
    position: Director & Co-founder
    text: Shubhodeep brings significant experience working in validation of very complex systems at leading semiconductor companies. Prior to founding Valtrix, Shubhodeep was working in Intel where he was involved in design validation of several x86 based client and server systems. In IBM, he was part of a RIS tool development team working on validation and characterization of IBM PowerPC processors, and co-authored numerous patents in the area of system validation techniques. He has a B.Tech. in ECE from the Indian Institute of Technology (IIT), Guwahati.
    img: dflt-team-pic.jpg
    social:
      - title: envelope #use for email address
        url: mailto:deepsrc@valtrix.in
      - title: twitter
        url: http://twitter.com/deepsrc
      - title: linkedin
        url: https://in.linkedin.com/pub/shubhodeep-roy-choudhury/6/a98/4a7
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Contact us message
contactmsg: "Leave us a message and we will get back to you in a jiffy" 

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO

gems:
  - jekyll-sitemap
